### PR TITLE
Dynamic and more descriptive navigation

### LINKED ISSUE #17: Make site navigation reusable
The site navigation is currently hard coded on each page. It should be a reusable component that's included on each page.

### LINKED ISSUE #18: Section nav should include the description for each sub-page

### PR DESCRIPTION
**Pull request by tempertemper**
### Adds
- New primary navigation partial
- Adds intro text for every content page
- Makes section navigation partial which includes intro text
- Uses a layout for section index pages

### Fixes
- Fixes some incorrect apostrophes
- Removes some unnecessarily raw HTML from a Markdown file

### CODE REVIEW

**Comment by tempertemper** [comment]
Bit of a bumper PR this one, covering 2 issues. I've added you both as reviewers as some is content (for @jonny-parker's eyes) and some is more technical (for @PaulSumner-Sage).

@PaulSumner-Sage On the technical front, I had a go at:

- Ordering the section navigation alphabetically based on the page title
- Defining the section variable dynamically

But both were proving a bit time consuming so I gave up and have raised separate Issues for these:

- [Order section navigation alphabetically by page title](https://github.com/tempertemper/html-playground/issues/23)
- [Come up with a more dynamic way to create section variable in navigation--section.html](https://github.com/tempertemper/html-playground/issues/24)

**Comment by tempertemper** [comment]
@jonny-parker @PaulSumner-Sage Just realised this PR is still here. Any chance you could get a quick look at it? If you can't get a look this week, I'm feeling fruity so I might just merge without a review 😜

**Review by jonny-parker — COMMENTED** [review]
Looks good from my quick check but your have conflicts it seems

**Comment by tempertemper** [comment]
> Looks good from my quick check but your have conflicts it seems

@jonny-parker Cool. Thanks! And I'll have a look at the merge conflicts 👍

**Review by PaulSumner-Sage — APPROVED** [review]

**Pull request merged**
